// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Driver struct {
	ID             int64          `json:"id"`
	Phone          string         `json:"phone"`
	HashedPassword string         `json:"hashed_password"`
	Name           string         `json:"name"`
	DateOfBirth    sql.NullTime   `json:"date_of_birth"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	Verified       bool           `json:"verified"`
	CreatedAt      time.Time      `json:"created_at"`
}
