// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: passenger.sql

package db

import (
	"context"
	"database/sql"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO driver (
  phone,
  hashed_password,
  name
) VALUES (
  $1, $2, $3
)
RETURNING id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at
`

type CreateDriverParams struct {
	Phone          string `json:"phone"`
	HashedPassword string `json:"hashed_password"`
	Name           string `json:"name"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, createDriver, arg.Phone, arg.HashedPassword, arg.Name)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDriver = `-- name: DeleteDriver :exec
DELETE FROM driver
WHERE phone = $1
`

func (q *Queries) DeleteDriver(ctx context.Context, phone string) error {
	_, err := q.db.ExecContext(ctx, deleteDriver, phone)
	return err
}

const getDriver = `-- name: GetDriver :one
SELECT id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at FROM driver
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDriver(ctx context.Context, id int64) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriver, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getDriverByPhone = `-- name: GetDriverByPhone :one
SELECT id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at FROM driver
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetDriverByPhone(ctx context.Context, phone string) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriverByPhone, phone)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getDriverForUpdate = `-- name: GetDriverForUpdate :one
SELECT id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at FROM driver
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetDriverForUpdate(ctx context.Context, id int64) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriverForUpdate, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const listDrivers = `-- name: ListDrivers :many
SELECT id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at FROM driver
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListDriversParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDrivers(ctx context.Context, arg ListDriversParams) ([]Driver, error) {
	rows, err := q.db.QueryContext(ctx, listDrivers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.HashedPassword,
			&i.Name,
			&i.DateOfBirth,
			&i.AvatarUrl,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriver = `-- name: UpdateDriver :one

UPDATE driver
SET phone = $2,
  name = $3,
  date_of_birth = $4
WHERE id = $1
RETURNING id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at
`

type UpdateDriverParams struct {
	ID          int64        `json:"id"`
	Phone       string       `json:"phone"`
	Name        string       `json:"name"`
	DateOfBirth sql.NullTime `json:"date_of_birth"`
}

// pagination: offset: skip many rows
func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, updateDriver,
		arg.ID,
		arg.Phone,
		arg.Name,
		arg.DateOfBirth,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE driver
SET hashed_password = $2
WHERE id = $1
RETURNING id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at
`

type UpdatePasswordParams struct {
	ID             int64  `json:"id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.ID, arg.HashedPassword)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const verify = `-- name: Verify :one
UPDATE driver
SET verified = true
WHERE phone = $1
RETURNING id, phone, hashed_password, name, date_of_birth, avatar_url, verified, created_at
`

func (q *Queries) Verify(ctx context.Context, phone string) (Driver, error) {
	row := q.db.QueryRowContext(ctx, verify, phone)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.HashedPassword,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}
